# # Model arguments
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
# model_revision: main
# torch_dtype: bfloat16
attn_implementation: flash_attention_2

# # Data training arguments
dataset_name: open-r1/OpenR1-Math-220k
# dataset_num_proc: 8

# # SFT trainer config
bf16: true
eval_strategy: "steps"
eval_steps: 100
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
use_flash_attn: true
# hub_model_id: meta-llama/Llama-3.1-8B
hub_strategy: every_save
learning_rate: 1.0e-04
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: true
max_length: 1024
max_steps: -1
num_train_epochs: 2
output_dir: data/Llama-3.1-8B-Instruct
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
# use_liger: false
warmup_ratio: 0.05
# use_cache: false
# # deepspeed: "src/zero3.yaml"